# Generated by Django 2.2.14 on 2020-07-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Potion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "invented_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invented_potions",
                        to="professors.Professor",
                    ),
                ),
            ],
            options={"db_table": "potions__potion",},
        ),
    ]
